//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BPNo4SynsTimeParer.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//



package com.cloud.mina.component.milink.bp;

import org.apache.mina.core.buffer.IoBuffer;

import com.cloud.mina.component.filter.MilinkBPComponent;
import com.cloud.mina.milink.bppackage.BPNo4SynsTimePackage;
import com.cloud.mina.milink.sportpackage.PackageData;


/** */
public class BPNo4SynsTimeParer extends MilinkBPComponent
{
	@Override
	public boolean check(IoBuffer buffer) {
		if(buffer.get(8)==4 && buffer.get(9)==0)
		{
			return true;
		}
		return false;
	}

	@Override
	public PackageData generateRealPackageData(IoBuffer buffer) {
		log.info(this.getClass().getSimpleName()+".generateRealPackageData() begin...");
		BPNo4SynsTimePackage data = new BPNo4SynsTimePackage();
		data.setName("bloodpressure");
		data.setType("no4");
		log.info(this.getClass().getSimpleName()+".generateRealPackageData() end.");
		return data;
	}
}
