//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MHDataPacketHandleStrategy.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//



package com.cloud.mina.milink.strategy;

import org.apache.mina.core.session.IoSession;

import com.cloud.mina.milink.sportpackage.PackageData;


/** */
public interface MHDataPacketHandleStrategy
{
    /** */
    public void handle(IoSession session, Object message);
}
