//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MilinkSportsPacketHandleStrategy.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//



package com.cloud.mina.milink.strategy;

import java.util.HashMap;
import java.util.Map;

import org.apache.mina.core.session.IoSession;

import com.cloud.mina.milink.sportpackage.PackageData;
import com.cloud.mina.milink.sportstate.SportLogoutState;
import com.cloud.mina.milink.sportstate.SportNo1LoginState;
import com.cloud.mina.milink.sportstate.SportNo8OneWayState;
import com.cloud.mina.milink.sportstate.SportNo8ThreeWayState;
import com.cloud.mina.milink.sportstate.SportNo8TwoWayState;
import com.cloud.mina.milink.sportstate.SportsPacketHandleState;

/** */
public class MilinkSportsPacketHandleStrategy implements MHDataPacketHandleStrategy
{
	@SuppressWarnings("rawtypes")
	private static Map<String,Class> classMap = new HashMap<String, Class>();
	SportsPacketHandleState state = null;
	public void setState(SportsPacketHandleState state) {
		this.state = state;
	}
	static
	{
		classMap.put("login", SportNo1LoginState.class);
		classMap.put("logout", SportLogoutState.class);
		classMap.put("No8-1", SportNo8OneWayState.class);
		classMap.put("No8-2", SportNo8TwoWayState.class);
		classMap.put("No8-3", SportNo8ThreeWayState.class);
		
	}
	public void handle(IoSession session, Object message) {
		
		boolean result = false;
		try {
			//changyaobin  工厂方法，获取各个数据包的对象
			if(message  !=null &&message instanceof PackageData  ){
				PackageData packageData=(PackageData) message;
				setState((SportsPacketHandleState) classMap.get(packageData.getType()).newInstance());
			}
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
		if(state!=null){
			state.handlePacket(session,message);
		}
	}
}
