//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoginPacket.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//



package com.cloud.mina.milink.sportpackage;


/** */
public class LoginPacket extends PackageData
{
	private String loginTime = "";
	public String getLoginTime() {
		return loginTime;
	}
	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}
}
