//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogoutPacket.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//

package com.cloud.mina.milink.sportpackage;

/** */
public class LogoutPacket extends PackageData {

}
