//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SportLogoutParser.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//



package com.cloud.mina.component.milink.sport;

import org.apache.mina.core.buffer.IoBuffer;

import com.cloud.mina.component.filter.MilinkSportComponent;
import com.cloud.mina.milink.sportpackage.LogoutPacket;
import com.cloud.mina.milink.sportpackage.PackageData;


/** */
public class SportLogoutParser extends MilinkSportComponent
{
	@Override
	public boolean check(IoBuffer buffer) {
		if(buffer.get(8)==1 && buffer.get(9)==3)
		{
			return true;
		}
		return false;
	}

	@Override
	public PackageData generateRealPackageData(IoBuffer buffer) {
		log.info(this.getClass().getSimpleName()+".generateRealPackageData() begin...");
		LogoutPacket packet = new LogoutPacket();
		packet.setName("sports");
		packet.setType("logout");
		log.info(this.getClass().getSimpleName()+".generateRealPackageData() end.");
		return packet;
	}
}
