//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BPNo1LoginPacket.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//

package com.cloud.mina.milink.bppackage;

import com.cloud.mina.milink.sportpackage.PackageData;


/** */
public class BPNo1LoginPacket extends PackageData
{
}
