//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ComponentIOFilter.java
//  @ Date : 2017/6/11
//  @ Author : 
//
//

package com.cloud.mina.component.filter;

import org.apache.mina.core.buffer.IoBuffer;
import org.apache.mina.core.filterchain.IoFilterAdapter;
import org.apache.mina.core.session.IoSession;

import com.cloud.mina.milink.sportpackage.PackageData;

/** */
public class ComponentIOFilter extends IoFilterAdapter {
	/** */
	public Component component;

	public ComponentIOFilter(Component component) {
		super();
		this.component = component;
	}

	@Override
	public void messageReceived(NextFilter nextFilter, IoSession session,
			Object message) throws Exception {
		// TODO Auto-generated method stub
		// 1.调用Component接口实现字节流转为Java对象 data = component.getDataFromBuffer(ioBuffer);
		// 2.递归调用messageReceived处理下一个设备 nextFilter.messageReceived(session, message);
		PackageData data = null;
		if (message instanceof IoBuffer) {
			IoBuffer ioBuffer = (IoBuffer) message;
			ioBuffer.setAutoExpand(true);
			data = component.getDataFromBuffer(ioBuffer);
		}
		if (data == null) {
			nextFilter.messageReceived(session, message);
		} else {
			nextFilter.messageReceived(session, data);
		}
	}
}
